name: run main.py

on:
  schedule:
    - cron: '45 3 * * 0-5'  # Every day at 3:45 AM UTC (9:30 AM NPT), excluding Saturday
    - cron: '45 12 * * 0-5' # Every day at 12:45 PM UTC (6:30 PM NPT), excluding Saturday
    - cron: '12 11 * * 0-5'  # Every day at 10:07 AM UTC (3:52 PM NPT), excluding Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          MY_SECRET_NAME: '98153'
        run: python main.py
            
      - name: commit files
        run: |
          git config --local user.email "ganesh.tiwari552@gmail.com"
          git config --local user.name "Ganesh Tiwari"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: Ganesh98153/python-script-schedule
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
